/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EducationLevel generated by hbm2java
 */
public class EducationLevel  implements java.io.Serializable {


     private Short idEducationLevel;
     private String educationLevel;
     private Set<EducationalQualification> educationalQualifications = new HashSet<EducationalQualification>(0);

    public EducationLevel() {
    }

	
    public EducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public EducationLevel(String educationLevel, Set<EducationalQualification> educationalQualifications) {
       this.educationLevel = educationLevel;
       this.educationalQualifications = educationalQualifications;
    }
   
    public Short getIdEducationLevel() {
        return this.idEducationLevel;
    }
    
    public void setIdEducationLevel(Short idEducationLevel) {
        this.idEducationLevel = idEducationLevel;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Set<EducationalQualification> getEducationalQualifications() {
        return this.educationalQualifications;
    }
    
    public void setEducationalQualifications(Set<EducationalQualification> educationalQualifications) {
        this.educationalQualifications = educationalQualifications;
    }




}


