/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EducationalQualification generated by hbm2java
 */
public class EducationalQualification  implements java.io.Serializable {


     private Integer idEducationalQualification;
     private EducationLevel educationLevel;
     private Person person;
     private String qualificationType;
     private String courseName;
     private String otherEducationLevel;
     private Boolean vocational;
     private String mainSubject;
     private String nameOfInstitution;
     private String country;
     private Date yearObtained;
     private String result;
     private String thesesTitle;
     private Boolean verified;
     private String howVerified;

    public EducationalQualification() {
    }

	
    public EducationalQualification(EducationLevel educationLevel, Person person, String qualificationType, String courseName) {
        this.educationLevel = educationLevel;
        this.person = person;
        this.qualificationType = qualificationType;
        this.courseName = courseName;
    }
    public EducationalQualification(EducationLevel educationLevel, Person person, String qualificationType, String courseName, String otherEducationLevel, Boolean vocational, String mainSubject, String nameOfInstitution, String country, Date yearObtained, String result, String thesesTitle, Boolean verified, String howVerified) {
       this.educationLevel = educationLevel;
       this.person = person;
       this.qualificationType = qualificationType;
       this.courseName = courseName;
       this.otherEducationLevel = otherEducationLevel;
       this.vocational = vocational;
       this.mainSubject = mainSubject;
       this.nameOfInstitution = nameOfInstitution;
       this.country = country;
       this.yearObtained = yearObtained;
       this.result = result;
       this.thesesTitle = thesesTitle;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
    public Integer getIdEducationalQualification() {
        return this.idEducationalQualification;
    }
    
    public void setIdEducationalQualification(Integer idEducationalQualification) {
        this.idEducationalQualification = idEducationalQualification;
    }
    public EducationLevel getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(EducationLevel educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getQualificationType() {
        return this.qualificationType;
    }
    
    public void setQualificationType(String qualificationType) {
        this.qualificationType = qualificationType;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public String getOtherEducationLevel() {
        return this.otherEducationLevel;
    }
    
    public void setOtherEducationLevel(String otherEducationLevel) {
        this.otherEducationLevel = otherEducationLevel;
    }
    public Boolean getVocational() {
        return this.vocational;
    }
    
    public void setVocational(Boolean vocational) {
        this.vocational = vocational;
    }
    public String getMainSubject() {
        return this.mainSubject;
    }
    
    public void setMainSubject(String mainSubject) {
        this.mainSubject = mainSubject;
    }
    public String getNameOfInstitution() {
        return this.nameOfInstitution;
    }
    
    public void setNameOfInstitution(String nameOfInstitution) {
        this.nameOfInstitution = nameOfInstitution;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getYearObtained() {
        return this.yearObtained;
    }
    
    public void setYearObtained(Date yearObtained) {
        this.yearObtained = yearObtained;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getThesesTitle() {
        return this.thesesTitle;
    }
    
    public void setThesesTitle(String thesesTitle) {
        this.thesesTitle = thesesTitle;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}



