/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1



/**
 * JobPreference generated by hbm2java
 */
public class JobPreference  implements java.io.Serializable {


     private Integer idJobPreference;
     private JobTitle jobTitle;
     private Person person;

    public JobPreference() {
    }

    public JobPreference(JobTitle jobTitle, Person person) {
       this.jobTitle = jobTitle;
       this.person = person;
    }
   
    public Integer getIdJobPreference() {
        return this.idJobPreference;
    }
    
    public void setIdJobPreference(Integer idJobPreference) {
        this.idJobPreference = idJobPreference;
    }
    public JobTitle getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(JobTitle jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }




}



