package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1



/**
 * JobPreference generated by hbm2java
 */
public class JobPreference  implements java.io.Serializable {


     private Integer idJobPreference;
     private JobTitle jobTitle;
     private Person person;

    public JobPreference() {
    }

    public JobPreference(JobTitle jobTitle, Person person) {
       this.jobTitle = jobTitle;
       this.person = person;
    }
   
    public Integer getIdJobPreference() {
        return this.idJobPreference;
    }
    
    public void setIdJobPreference(Integer idJobPreference) {
        this.idJobPreference = idJobPreference;
    }
    public JobTitle getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(JobTitle jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }




}


