package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonTitle generated by hbm2java
 */
public class PersonTitle  implements java.io.Serializable {


     private Integer idpersonTitle;
     private String title;
     private Set<Person> persons = new HashSet<Person>(0);

    public PersonTitle() {
    }

    public PersonTitle(String title, Set<Person> persons) {
       this.title = title;
       this.persons = persons;
    }
   
    public Integer getIdpersonTitle() {
        return this.idpersonTitle;
    }
    
    public void setIdpersonTitle(Integer idpersonTitle) {
        this.idpersonTitle = idpersonTitle;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


