package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonContactMode generated by hbm2java
 */
public class PersonContactMode  implements java.io.Serializable {


     private Integer idcontactPreference;
     private String contactMode;
     private Set<Person> persons = new HashSet<Person>(0);

    public PersonContactMode() {
    }

	
    public PersonContactMode(String contactMode) {
        this.contactMode = contactMode;
    }
    public PersonContactMode(String contactMode, Set<Person> persons) {
       this.contactMode = contactMode;
       this.persons = persons;
    }
   
    public Integer getIdcontactPreference() {
        return this.idcontactPreference;
    }
    
    public void setIdcontactPreference(Integer idcontactPreference) {
        this.idcontactPreference = idcontactPreference;
    }
    public String getContactMode() {
        return this.contactMode;
    }
    
    public void setContactMode(String contactMode) {
        this.contactMode = contactMode;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


