package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonStatus generated by hbm2java
 */
public class PersonStatus  implements java.io.Serializable {


     private Integer idpersonStatus;
     private String personStatus;
     private Set<Person> persons = new HashSet<Person>(0);

    public PersonStatus() {
    }

    public PersonStatus(String personStatus, Set<Person> persons) {
       this.personStatus = personStatus;
       this.persons = persons;
    }
   
    public Integer getIdpersonStatus() {
        return this.idpersonStatus;
    }
    
    public void setIdpersonStatus(Integer idpersonStatus) {
        this.idpersonStatus = idpersonStatus;
    }
    public String getPersonStatus() {
        return this.personStatus;
    }
    
    public void setPersonStatus(String personStatus) {
        this.personStatus = personStatus;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


