package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RefereeRelationship generated by hbm2java
 */
public class RefereeRelationship  implements java.io.Serializable {


     private Integer idrefereeRelationship;
     private String relationship;
     private Set<Referee> referees = new HashSet<Referee>(0);

    public RefereeRelationship() {
    }

    public RefereeRelationship(String relationship, Set<Referee> referees) {
       this.relationship = relationship;
       this.referees = referees;
    }
   
    public Integer getIdrefereeRelationship() {
        return this.idrefereeRelationship;
    }
    
    public void setIdrefereeRelationship(Integer idrefereeRelationship) {
        this.idrefereeRelationship = idrefereeRelationship;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public Set<Referee> getReferees() {
        return this.referees;
    }
    
    public void setReferees(Set<Referee> referees) {
        this.referees = referees;
    }




}


