package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1



/**
 * Referee generated by hbm2java
 */
public class Referee  implements java.io.Serializable {


     private Integer idReferee;
     private Person person;
     private RefereeRelationship refereeRelationship;
     private String title;
     private String forename;
     private String surname;
     private String email;
     private String contactPhone;
     private Boolean permissionToContact;
     private Boolean permissionToStoreDetail;
     private Boolean verified;
     private String howVerified;
     private String referenceDoc;

    public Referee() {
    }

	
    public Referee(Person person, RefereeRelationship refereeRelationship, String forename, String surname) {
        this.person = person;
        this.refereeRelationship = refereeRelationship;
        this.forename = forename;
        this.surname = surname;
    }
    public Referee(Person person, RefereeRelationship refereeRelationship, String title, String forename, String surname, String email, String contactPhone, Boolean permissionToContact, Boolean permissionToStoreDetail, Boolean verified, String howVerified, String referenceDoc) {
       this.person = person;
       this.refereeRelationship = refereeRelationship;
       this.title = title;
       this.forename = forename;
       this.surname = surname;
       this.email = email;
       this.contactPhone = contactPhone;
       this.permissionToContact = permissionToContact;
       this.permissionToStoreDetail = permissionToStoreDetail;
       this.verified = verified;
       this.howVerified = howVerified;
       this.referenceDoc = referenceDoc;
    }
   
    public Integer getIdReferee() {
        return this.idReferee;
    }
    
    public void setIdReferee(Integer idReferee) {
        this.idReferee = idReferee;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public RefereeRelationship getRefereeRelationship() {
        return this.refereeRelationship;
    }
    
    public void setRefereeRelationship(RefereeRelationship refereeRelationship) {
        this.refereeRelationship = refereeRelationship;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public Boolean getPermissionToContact() {
        return this.permissionToContact;
    }
    
    public void setPermissionToContact(Boolean permissionToContact) {
        this.permissionToContact = permissionToContact;
    }
    public Boolean getPermissionToStoreDetail() {
        return this.permissionToStoreDetail;
    }
    
    public void setPermissionToStoreDetail(Boolean permissionToStoreDetail) {
        this.permissionToStoreDetail = permissionToStoreDetail;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }
    public String getReferenceDoc() {
        return this.referenceDoc;
    }
    
    public void setReferenceDoc(String referenceDoc) {
        this.referenceDoc = referenceDoc;
    }




}


