/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1



/**
 * Referee generated by hbm2java
 */
public class Referee  implements java.io.Serializable {


     private Integer idReferee;
     private Person person;
     private String title;
     private String forename;
     private String surname;
     private String email;
     private String contactPhone;
     private String relationship;
     private Boolean permissionToContact;
     private Boolean permissionToStoreDetail;
     private Boolean verified;
     private String howVerified;
     private String referenceDoc;

    public Referee() {
    }

	
    public Referee(Person person, String forename, String surname) {
        this.person = person;
        this.forename = forename;
        this.surname = surname;
    }
    public Referee(Person person, String title, String forename, String surname, String email, String contactPhone, String relationship, Boolean permissionToContact, Boolean permissionToStoreDetail, Boolean verified, String howVerified, String referenceDoc) {
       this.person = person;
       this.title = title;
       this.forename = forename;
       this.surname = surname;
       this.email = email;
       this.contactPhone = contactPhone;
       this.relationship = relationship;
       this.permissionToContact = permissionToContact;
       this.permissionToStoreDetail = permissionToStoreDetail;
       this.verified = verified;
       this.howVerified = howVerified;
       this.referenceDoc = referenceDoc;
    }
   
    public Integer getIdReferee() {
        return this.idReferee;
    }
    
    public void setIdReferee(Integer idReferee) {
        this.idReferee = idReferee;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public Boolean getPermissionToContact() {
        return this.permissionToContact;
    }
    
    public void setPermissionToContact(Boolean permissionToContact) {
        this.permissionToContact = permissionToContact;
    }
    public Boolean getPermissionToStoreDetail() {
        return this.permissionToStoreDetail;
    }
    
    public void setPermissionToStoreDetail(Boolean permissionToStoreDetail) {
        this.permissionToStoreDetail = permissionToStoreDetail;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }
    public String getReferenceDoc() {
        return this.referenceDoc;
    }
    
    public void setReferenceDoc(String referenceDoc) {
        this.referenceDoc = referenceDoc;
    }




}



