package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Skill generated by hbm2java
 */
public class Skill  implements java.io.Serializable {


     private Integer idSkill;
     private String skillName;
     private Set<SkillPerson> skillPersons = new HashSet<SkillPerson>(0);

    public Skill() {
    }

	
    public Skill(String skillName) {
        this.skillName = skillName;
    }
    public Skill(String skillName, Set<SkillPerson> skillPersons) {
       this.skillName = skillName;
       this.skillPersons = skillPersons;
    }
   
    public Integer getIdSkill() {
        return this.idSkill;
    }
    
    public void setIdSkill(Integer idSkill) {
        this.idSkill = idSkill;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public Set<SkillPerson> getSkillPersons() {
        return this.skillPersons;
    }
    
    public void setSkillPersons(Set<SkillPerson> skillPersons) {
        this.skillPersons = skillPersons;
    }




}


