package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SkillLevel generated by hbm2java
 */
public class SkillLevel  implements java.io.Serializable {


     private Integer idskillLevel;
     private String skillLevel;
     private Set<SkillPerson> skillPersons = new HashSet<SkillPerson>(0);

    public SkillLevel() {
    }

    public SkillLevel(String skillLevel, Set<SkillPerson> skillPersons) {
       this.skillLevel = skillLevel;
       this.skillPersons = skillPersons;
    }
   
    public Integer getIdskillLevel() {
        return this.idskillLevel;
    }
    
    public void setIdskillLevel(Integer idskillLevel) {
        this.idskillLevel = idskillLevel;
    }
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }
    public Set<SkillPerson> getSkillPersons() {
        return this.skillPersons;
    }
    
    public void setSkillPersons(Set<SkillPerson> skillPersons) {
        this.skillPersons = skillPersons;
    }




}


