/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Skill generated by hbm2java
 */
public class Skill  implements java.io.Serializable {


     private Integer idSkill;
     private String skillName;
     private Set<SkillPerson> skillPersons = new HashSet<SkillPerson>(0);

    public Skill() {
    }

	
    public Skill(String skillName) {
        this.skillName = skillName;
    }
    public Skill(String skillName, Set<SkillPerson> skillPersons) {
       this.skillName = skillName;
       this.skillPersons = skillPersons;
    }
   
    public Integer getIdSkill() {
        return this.idSkill;
    }
    
    public void setIdSkill(Integer idSkill) {
        this.idSkill = idSkill;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public Set<SkillPerson> getSkillPersons() {
        return this.skillPersons;
    }
    
    public void setSkillPersons(Set<SkillPerson> skillPersons) {
        this.skillPersons = skillPersons;
    }




}


