/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1



/**
 * SkillPerson generated by hbm2java
 */
public class SkillPerson  implements java.io.Serializable {


     private Integer idSkillPerson;
     private Person person;
     private Skill skill;
     private String skillLevel;
     private Boolean verified;
     private String howVerified;

    public SkillPerson() {
    }

	
    public SkillPerson(Person person, Skill skill) {
        this.person = person;
        this.skill = skill;
    }
    public SkillPerson(Person person, Skill skill, String skillLevel, Boolean verified, String howVerified) {
       this.person = person;
       this.skill = skill;
       this.skillLevel = skillLevel;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
    public Integer getIdSkillPerson() {
        return this.idSkillPerson;
    }
    
    public void setIdSkillPerson(Integer idSkillPerson) {
        this.idSkillPerson = idSkillPerson;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}


