/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int idUser;
     private UserType userType;
     private String username;
     private String password;
     private Date registerDate;
     private Set<Person> persons = new HashSet<Person>(0);

    public User() {
    }

	
    public User(int idUser, UserType userType, String username, String password) {
        this.idUser = idUser;
        this.userType = userType;
        this.username = username;
        this.password = password;
    }
    public User(int idUser, UserType userType, String username, String password, Date registerDate, Set<Person> persons) {
       this.idUser = idUser;
       this.userType = userType;
       this.username = username;
       this.password = password;
       this.registerDate = registerDate;
       this.persons = persons;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}



