/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv_gn.model;

/**
 *
 * @author Ganith Perera
 */
// Generated Apr 10, 2017 11:21:51 PM by Hibernate Tools 4.3.1


import com.cv_gn.util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Short idUserType;
     private String userType;
     private Set<User> users = new HashSet<User>(0);
     private static PreparedStatement preparedStatement=null;
     
             

    public UserType() {
         
    }

	
    public UserType(String userType) {
        this.userType = userType;
    }
    public UserType(String userType, Set<User> users) {
       this.userType = userType;
       this.users = users;
    }
   
    public Short getIdUserType() {        
        return this.idUserType;
    }
     public Short getIdUserType(int iduser_type, Connection con) throws SQLException {
       
         String idUserTypeQry = "select iduser_type from user_type where user_type='" + iduser_type+ "'";
         preparedStatement=con.prepareStatement(idUserTypeQry);
         ResultSet rs=preparedStatement.executeQuery();
         idUserType=(short)rs.getInt(1);
        return this.idUserType;
    }
    
    public void setIdUserType(Short idUserType) {        
        this.idUserType = idUserType;
    }
    public String getUserType() {
        
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}



