package com.cv_gn.model;
// Generated May 1, 2017 11:12:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Short idUserType;
     private String userType;
     private Set<User> users = new HashSet<User>(0);

    public UserType() {
    }

	
    public UserType(String userType) {
        this.userType = userType;
    }
    public UserType(String userType, Set<User> users) {
       this.userType = userType;
       this.users = users;
    }
   
    public Short getIdUserType() {
        return this.idUserType;
    }
    
    public void setIdUserType(Short idUserType) {
        this.idUserType = idUserType;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


